version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
volumes:
  dbdata: 
